---
- name: Installing the required softwares. Then the project will be ready to use.
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Installing Python3
    apt:
      name: python3
      state: latest
      update_cache: yes
  - name: Installing Flask
    apt:
      name: python3-flask
      state: latest
  - name: Copying the Flask app
    copy:
      src: /$PWD/hello.py
      dest: /home/vagrant/hello.py
  - name:
    shell: cd /home/vagrant
  - name: Running the Flask app
    shell: flask run --host 0.0.0.0
    environment:
      FLASK_APP: /home/vagrant/hello.py