---
- name: Installing the required softwares. Then the project will be ready to use.
  hosts: all
  gather_facts: no
  become: yes

  tasks:
  - name: Installing Python3
    apt:
      name: python3
      state: latest
      update_cache: yes
  - name: Installing Flask
    apt:
      name: python3-flask
      state: latest
  - name:
    shell: cd /home/vagrant/project
  - name: Running the Flask app
    shell: nohup flask run --host 0.0.0.0 > flask_log.txt 2>&1 &
    environment:
      FLASK_APP: /home/vagrant/project/hello.py
